repos:
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
      - id: markdown-link-check
        args:
          - --quiet
          - --config=md_link_check_config.json
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell

  # -   repo: https://github.com/shellcheck-py/shellcheck-py
  #     rev: v0.11.0.1
  #     hooks:
  #     -   id: shellcheck
